---

- hosts: all
  become: true
  pre_tasks:

  - name: Update repository index
    tags: always
    package:
      update_cache: yes
    changed_when: false

# This playbook or taskbook should be put into the bootstrap.yml for a better automation experience
- hosts: all
  become: true
  roles:
    - base

- hosts: ansible_server
  become: true
  roles:
    - ansible_server

- hosts: db_server
  become: true
  roles:
    - db_server

- hosts: samba_share
  become: true
  roles:
    - samba_share

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: reverse_proxy
  become: true
  roles: 
    - reverse_proxy
