- name: install mariadb
  tags: mariadb, centos
  dnf:
    name:
      - mariadb-server
      - python3-mysqlclient
    state: latest

- name: enable mariadb
  tags: mariadb
  service:
    name: mariadb
    state: started
    enabled: yes

- name: copy passwords.yml
  tags: centos
  template:
    src: passwords.yml.j2
    dest: /home/gloat/passwords.yml

- name: read mariadb root password
  tags: mariadb
  slurp:
    src: "{{ mariadb_root_password_file }}"
  register: mariadb_root_pass

- name: create mysql database
  tags: mariadb
  mysql_db:
    name: production
    state: present
    login_user: root
    login_password: "{{ mariadb_root_pass.content | b64decode }}"

