# This is meant for a workstation where you install all your required packages and setup configuration
- name: Install packages
  tags: ubuntu, ansible_server
  apt:
    name: 
      - unzip
      - neovim
      - curl
      - git
    state: latest

- name: Install terraform
  tags: ansible_server
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.8.0/terraform_1.8.0_linux_amd64.zip
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
    remote_src: yes

- name: Download brave gpg key
  tags: ansible_server
  get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    mode: 0644

- name: Add brave repository to list
  tags: ubuntu, ansible_server
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
    state: present

- name: Update cache and install brave
  tags: ubuntu, ansible_server
  apt:
    name: brave-browser
    update_cache: yes
    state: latest
